### ISSUE TITLE
It looks like the code here is outdated

### ISSUE THREAD

**Issue by cocotyty** [beorn7/histogram_experiments#1]

**Comment by beorn7** [comment]
Err… I mean, it's just hacking around. But outdated? Could you be more specific?

**Comment by cocotyty** [comment]
> Err… I mean, it's just hacking around. But outdated? Could you be more specific?

No,it's not outdated.

Sorry, the translation software I'm using may not be very accurate.

I mean that it cannot works with newest prometheus sparse histogram.

**Comment by cocotyty** [comment]
Thank you for your awesome sparse histogram 👍
